import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiArrowDownTray,
  HiChevronLeft,
  HiChevronRight,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiBriefcaseDuotone,
  PiTrophyDuotone,
  PiEnvelopeDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiLaravel,
  SiNodedotjs,
  SiFlutter,
  SiMysql,
  SiPhp,
  SiHtml5,
  SiCss3,
  SiPython,
  SiTensorflow,
  SiAmazon,
  SiAwslambda,
  SiOpensearch,
  SiPostgresql,
  SiRedis,
  SiFastapi,
  SiDart,
  SiFirebase,
  SiExpress,
  SiSocketdotio,
  SiMongodb,
  SiGooglemaps,
  SiArduino,
  SiTailwindcss,
  SiTypescript,
  SiOpenai,
  SiGooglecloud,
} from "react-icons/si";

import { FaJava } from "react-icons/fa";
import { TbApi } from "react-icons/tb";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, FaEnvelope, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: FaEnvelope,
  envelope: PiEnvelopeDuotone,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  briefcase: PiBriefcaseDuotone,
  trophy: PiTrophyDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  download: HiArrowDownTray,
  chevronLeft: HiChevronLeft,
  chevronRight: HiChevronRight,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  react: SiReact,
  laravel: SiLaravel,
  nodejs: SiNodedotjs,
  flutter: SiFlutter,
  java: FaJava,
  mysql: SiMysql,
  php: SiPhp,
  html: SiHtml5,
  css: SiCss3,
  python: SiPython,
  tensorflow: SiTensorflow,
  aws: SiAmazon,
  lambda: SiAwslambda,
  opensearch: SiOpensearch,
  postgresql: SiPostgresql,
  redis: SiRedis,
  fastapi: SiFastapi,
  dart: SiDart,
  firebase: SiFirebase,
  express: SiExpress,
  socketio: SiSocketdotio,
  mongodb: SiMongodb,
  maps: SiGooglemaps,
  arduino: SiArduino,
  tailwind: SiTailwindcss,
  typescript: SiTypescript,
  openai: SiOpenai,
  googlecloud: SiGooglecloud,
  api: TbApi,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
